project:
  type: website
  output-dir: _site

website:
  title: Abderrahmen Dhif
  favicon: img/logo.png
  page-navigation: true
  google-analytics: "G-N3H9QQKM0Q"
  cookie-consent: 
    type: express 
    style: interstitial 
    palette: dark
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa solid user >}} About" 
      - href: about.qmd
        text: "{{< fa solid file >}} CV"  
      - href: blog.qmd
        text: "{{< fa solid pencil >}} Blog" 
    right: 
      - href: https://www.linkedin.com/in/abderrahmen-dhif-84011873/
        icon: linkedin
          target: _blank
      - href: mailto:dhif.abderramen@gmail.com
        icon: envelope
          target: _blank
      - href: https://github.com/AbderrahmenDHIF
        icon: github
          target: _blank
         

       

  page-footer: 
    left: "© 2023 Abderrahmen DHIF"

format:
   html:
    highlight-style: a11y
    theme: solar
    light: flatly
    dark: slate
    css: styles.css

execute:
  freeze: auto   



