project:
  type: website
  output-dir: _site

website:
  title: Abderrahmen Dhif
  favicon: img/logo.png
  page-navigation: true
  google-analytics: "G-N3H9QQKM0Q"
  cookie-consent: 
    type: express 
    style: interstitial 
    palette: dark
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa solid user >}} About" 
      - href: about.qmd
        text: "{{< fa solid file >}} CV"  
      - href: blog.qmd
        text: "{{< fa solid pencil >}} Blog" 

  page-footer: 
    left: "© 2023 Abderrahmen DHIF"

format:
   html:
    highlight-style: a11y
    theme: solar
    light: flatly
    dark: slate
    css: styles.css

execute:
  freeze: auto   



