project:
  type: website
  output-dir: _site

website:
  title: Abderrahmen Dhif
  favicon: img/logo.png
  page-navigation: true
  google-analytics: "G-N3H9QQKM0Q"
  cookie-consent: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV

format:
   html:
    highlight-style: a11y
    theme: solar
    light: flatly
    dark: slate
    css: styles.css

execute:
  freeze: auto   



