project:
  type: website
  output-dir: _site

website:
  title: Abderrahmen Dhif
  favicon: img/logo.png
  page-navigation: true
  google-analytics: "G-N3H9QQKM0Q"
  cookie-consent: 
    type: express 
    style: interstitial 
    palette: dark
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa solid user >}} About" 
      - href: about.qmd
        text: "{{< fa solid file >}} CV"  
      - href: blog.qmd
        text: "{{< fa solid pencil >}} Blog" 
    right: 
      - icon: linkedin
        target: _blank
        href: https://www.linkedin.com/in/abderrahmen-dhif-84011873/
      - href: mailto:dhif.abderramen@gmail.com
        icon: envelope
        target: _blank
      - href: https://github.com/AbderrahmenDHIF
        icon: github
        target: _blank
         

       

  page-footer: 
    left: "© 2023 Abderrahmen DHIF"

format:
   html:
    highlight-style: a11y
    theme: 
      light: [cosmo,ligh.scss,img/DSS2-light.png]
      dark: [cosmo,dark.scss,img/DSS2-dark.png]
    css: style_g.css

execute:
  freeze: auto   

include-after-body:
  text: |
    <script type="application/javascript" src="script.js"></script>
resources: 
  - img/*

